# Generated by Django 3.2.5 on 2021-07-13 15:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('company_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_app.companytype')),
            ],
        ),
    ]
